name: Build, test and publish

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      scala_version:
        required: true
        type: string
      sbt_commands:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: 'sbt'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and test
        run: sbt ++${{ inputs.scala_version }} ${{ inputs.sbt_commands }}

      - name: Docker Push PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -e
          PULL_TAG="pull-${{ github.event.number }}"          
          docker tag ${{ github.repository }} ${{ github.repository }}:${PULL_TAG} && docker push ${{ github.repository }}:${PULL_TAG}

      - name: Docker Push Tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          set -e
          for tag in ${{ github.ref_name }} latest; do
            docker tag ${{ github.repository }} ${{ github.repository }}:${tag} && docker push ${{ github.repository }}:${tag}
          done
      
